// <auto-generated />
using System;
using Hotel.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotel.Persistence.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20220707163902_InitRoom")]
    partial class InitRoom
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("Hotel.Domain.Human", b =>
                {
                    b.Property<Guid>("HumanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HumanId");

                    b.HasIndex("HumanId")
                        .IsUnique();

                    b.ToTable("Humans");
                });

            modelBuilder.Entity("Hotel.Domain.Room", b =>
                {
                    b.Property<Guid>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomFloor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomPlaces")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomPriceDefault")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
